# Generated by Django 4.2.30 on 2026-06-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('deputy', 'Deputy'), ('lab', 'Lab')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('bag_id', models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('donor', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=10)),
                ('qty', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('expiry', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_bloodbag',
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('blood_type', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('available', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('issued', models.IntegerField(default=0)),
                ('expired', models.IntegerField(default=0)),
                ('critical_limit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Blood inventory',
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('request_id', models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=255)),
                ('blood', models.CharField(max_length=5)),
                ('qty', models.IntegerField(default=1)),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_bloodrequest',
            },
        ),
        migrations.CreateModel(
            name='DisposalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_code', models.CharField(max_length=20)),
                ('disposal_type', models.CharField(db_column='type', max_length=100)),
                ('blood', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('worker', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, default='', max_length=20)),
                ('blood', models.CharField(max_length=5)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('total_count', models.IntegerField(default=0)),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_donor',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(default='Connected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=255)),
                ('blood', models.CharField(max_length=5)),
                ('qty', models.IntegerField(default=1)),
                ('priority', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('delivery_notes', models.CharField(blank=True, default='', max_length=500)),
                ('delivered_by', models.CharField(max_length=255)),
                ('delivered_at', models.DateField()),
            ],
            options={
                'ordering': ['-delivered_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('seen_by', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notification_type', models.CharField(db_column='type', max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('singleton_key', models.CharField(default='default', max_length=20, primary_key=True, serialize=False)),
                ('total_rooms', models.IntegerField(default=3)),
                ('total_fridges_per_room', models.IntegerField(default=2)),
                ('total_shelves_per_fridge', models.IntegerField(default=4)),
                ('capacity_per_shelf', models.IntegerField(default=100)),
                ('room_names', models.JSONField(default=list)),
                ('details', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StorageRoom',
            fields=[
                ('room', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('used', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PendingDonor',
            fields=[
                ('bag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pending_donor', serialize=False, to='api.bloodbag')),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('room', models.CharField(max_length=50)),
                ('fridge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageFridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_id', models.CharField(max_length=50)),
                ('used', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_set', to='api.storageroom')),
            ],
            options={
                'unique_together': {('room', 'fridge_id')},
            },
        ),
    ]
