# Generated by Django 4.2.30 on 2026-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog_account_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=128, unique=True)),
                ('allowed_role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('deputy', 'Branch_Deputy'), ('lab', 'Lab')], default='lab', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device access',
                'verbose_name_plural': 'Device access records',
                'ordering': ['-last_seen', '-created_at'],
            },
        ),
    ]
