# Generated by Django 4.2.30 on 2026-06-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_name',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.account'),
        ),
    ]
