# Generated by Django 4.2.30 on 2026-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_disposal_donor_diseases_output_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodbag',
            name='expiry',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodbag',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='قيد المراجعة', max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
